using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Chuvadi.Sheets.Zip;

namespace Chuvadi.Sheets.ManualTests;

/// <summary>
/// Exercises the public Zip API end-to-end.
///
/// Produces and verifies several zip files:
///   1. zip_extensions.zip — created with the extension methods (.ToZip on string[]).
///   2. zip_directory.zip  — full directory zip via .ZipDirectory.
///   3. zip_writer.zip     — created with the ZipWriter streaming API.
///   4. zip_async.zip      — same content, built via async API.
///   5. Extract-back round-trip — verifies bytes are identical after extract.
///   6. Zip-slip protection — attempts a malicious ../../ entry and verifies the writer rejects it.
///   7. ListZipEntries — verifies metadata is reported correctly.
/// </summary>
internal static class ZipExtensionTest
{
    public static void Run(string outputDir)
    {
        Console.WriteLine("[ZipExtensionTest] Running zip tests...");
        Console.WriteLine();

        int pass = 0;
        int fail = 0;

        void Check(string label, Action body)
        {
            try
            {
                body();
                Console.WriteLine($"    PASS: {label}");
                pass++;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"    FAIL: {label}");
                Console.WriteLine($"          {ex.GetType().Name}: {ex.Message}");
                fail++;
            }
        }

        // ---- Set up: source files ---------------------------------------------------
        var srcDir = Path.Combine(outputDir, "zip_source");
        if (Directory.Exists(srcDir)) Directory.Delete(srcDir, recursive: true);
        Directory.CreateDirectory(srcDir);

        var file1 = Path.Combine(srcDir, "alpha.txt");
        var file2 = Path.Combine(srcDir, "beta.txt");
        var subDir = Path.Combine(srcDir, "sub");
        Directory.CreateDirectory(subDir);
        var file3 = Path.Combine(subDir, "gamma.bin");

        File.WriteAllText(file1, "Hello from alpha — this is a test file.\n");
        File.WriteAllText(file2, "Beta has multiple\nlines\nand UTF-8: सुप्रभात\n");
        File.WriteAllBytes(file3, new byte[] { 0x00, 0x01, 0x02, 0xFF, 0xFE, 0xFD });

        // ---- 1. IEnumerable<string>.ToZip(...) -------------------------------------
        Check("IEnumerable<string>.ToZip → creates archive", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_extensions.zip");
            if (File.Exists(zipPath)) File.Delete(zipPath);

            new[] { file1, file2, file3 }.ToZip(zipPath);

            if (!File.Exists(zipPath)) throw new Exception("Zip not created.");
            if (new FileInfo(zipPath).Length < 10) throw new Exception("Zip implausibly small.");

            // Entries named by basename only (per spec we set).
            var entries = zipPath.ListZipEntries();
            if (entries.Count != 3) throw new Exception($"Expected 3 entries, got {entries.Count}");
            var names = entries.Select(e => e.Name).OrderBy(s => s).ToArray();
            if (names[0] != "alpha.txt") throw new Exception($"Entry 0: {names[0]}");
            if (names[1] != "beta.txt") throw new Exception($"Entry 1: {names[1]}");
            if (names[2] != "gamma.bin") throw new Exception($"Entry 2: {names[2]}");
        });

        // ---- 2. ZipDirectory ------------------------------------------------------
        Check("string.ZipDirectory → preserves directory tree", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_directory.zip");
            if (File.Exists(zipPath)) File.Delete(zipPath);

            srcDir.ZipDirectory(zipPath);

            var entries = zipPath.ListZipEntries();
            if (entries.Count != 3) throw new Exception($"Expected 3 entries, got {entries.Count}");

            // Sub-directory entries should be "sub/gamma.bin", not "sub\\gamma.bin".
            var hasSubEntry = entries.Any(e => e.Name == "sub/gamma.bin");
            if (!hasSubEntry)
                throw new Exception($"Expected 'sub/gamma.bin'; got entries: {string.Join(", ", entries.Select(e => e.Name))}");
        });

        // ---- 3. ZipWriter streaming API -------------------------------------------
        Check("ZipWriter.Create → AddFile/AddText/AddBytes/AddStream", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_writer.zip");
            if (File.Exists(zipPath)) File.Delete(zipPath);

            using (var zip = ZipWriter.Create(zipPath))
            {
                zip.AddFile("alpha.txt", file1);
                zip.AddText("readme.txt", "Generated by Chuvadi.Sheets");
                zip.AddBytes("raw/data.bin", new byte[] { 0xCA, 0xFE, 0xBA, 0xBE });

                using var ms = new MemoryStream(Encoding.UTF8.GetBytes("from stream"));
                zip.AddStream("stream.txt", ms);
            }

            var entries = zipPath.ListZipEntries();
            if (entries.Count != 4) throw new Exception($"Expected 4 entries, got {entries.Count}");

            var names = entries.Select(e => e.Name).OrderBy(s => s).ToArray();
            if (names[0] != "alpha.txt") throw new Exception($"Names: {string.Join(",", names)}");
            if (names[3] != "stream.txt") throw new Exception($"Names: {string.Join(",", names)}");
        });

        // ---- 4. Async API ---------------------------------------------------------
        Check("Async write → same content as sync", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_async.zip");
            if (File.Exists(zipPath)) File.Delete(zipPath);

            // Use the sync wrapper of the async API to avoid an await pyramid in this test.
            new[] { file1, file2, file3 }
                .ToZipAsync(zipPath)
                .GetAwaiter().GetResult();

            var entries = zipPath.ListZipEntries();
            if (entries.Count != 3) throw new Exception($"Expected 3 entries, got {entries.Count}");
        });

        // ---- 5. Extract round-trip ------------------------------------------------
        Check("Extract round-trip preserves bytes", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_writer.zip");
            var extractDir = Path.Combine(outputDir, "zip_extracted");
            if (Directory.Exists(extractDir)) Directory.Delete(extractDir, recursive: true);

            zipPath.ExtractTo(extractDir);

            // alpha.txt should match file1's content byte-for-byte.
            var extractedAlpha = Path.Combine(extractDir, "alpha.txt");
            if (!File.Exists(extractedAlpha)) throw new Exception("alpha.txt not extracted.");
            var srcBytes = File.ReadAllBytes(file1);
            var dstBytes = File.ReadAllBytes(extractedAlpha);
            if (!srcBytes.SequenceEqual(dstBytes))
                throw new Exception($"alpha.txt bytes differ after round trip: {srcBytes.Length} vs {dstBytes.Length}");

            // readme.txt should contain "Generated by Chuvadi.Sheets".
            var readme = File.ReadAllText(Path.Combine(extractDir, "readme.txt"));
            if (readme != "Generated by Chuvadi.Sheets")
                throw new Exception($"readme.txt content: '{readme}'");

            // raw/data.bin should be the 4 bytes we wrote.
            var binPath = Path.Combine(extractDir, "raw", "data.bin");
            if (!File.Exists(binPath)) throw new Exception("raw/data.bin not extracted.");
            var binBytes = File.ReadAllBytes(binPath);
            if (binBytes.Length != 4 || binBytes[0] != 0xCA || binBytes[3] != 0xBE)
                throw new Exception($"raw/data.bin bytes: [{string.Join(",", binBytes.Select(b => b.ToString("X2")))}]");
        });

        // ---- 6. Path-traversal protection on write -------------------------------
        Check("ZipWriter rejects '..' entries", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_evil.zip");
            if (File.Exists(zipPath)) File.Delete(zipPath);

            using var zip = ZipWriter.Create(zipPath);
            try
            {
                zip.AddText("../../etc/passwd", "evil");
                throw new Exception("Expected ArgumentException for '..' entry, none thrown.");
            }
            catch (ArgumentException)
            {
                // expected
            }
        });

        // ---- 7. Path-traversal protection on extract -----------------------------
        // This test crafts a malicious zip by hand (using BCL directly) to confirm
        // the extractor refuses to write outside the target. Skips on platforms where
        // crafting such a zip would be awkward.
        Check("ZipReader.ExtractTo refuses zip-slip entries", () =>
        {
            var evilZipPath = Path.Combine(outputDir, "zip_evil_extract.zip");
            if (File.Exists(evilZipPath)) File.Delete(evilZipPath);

            // Build a malicious zip directly via BCL, bypassing our writer's protection.
            using (var s = new FileStream(evilZipPath, FileMode.Create))
            using (var archive = new ZipArchive(s, ZipArchiveMode.Create))
            {
                var entry = archive.CreateEntry("../escaped.txt");
                using var w = new StreamWriter(entry.Open());
                w.Write("I should not be written here");
            }

            var targetDir = Path.Combine(outputDir, "zip_evil_target");
            if (Directory.Exists(targetDir)) Directory.Delete(targetDir, recursive: true);

            try
            {
                evilZipPath.ExtractTo(targetDir);
                throw new Exception("Expected ZipFormatException for zip-slip, none thrown.");
            }
            catch (ZipFormatException)
            {
                // expected
            }
        });

        // ---- 8. ListZipEntries metadata ----------------------------------------
        Check("ListZipEntries returns name + size", () =>
        {
            var zipPath = Path.Combine(outputDir, "zip_writer.zip");
            var entries = zipPath.ListZipEntries();
            var alpha = entries.FirstOrDefault(e => e.Name == "alpha.txt");
            if (alpha is null) throw new Exception("alpha.txt entry not found.");
            if (alpha.Size != new FileInfo(file1).Length)
                throw new Exception($"alpha.txt Size: expected {new FileInfo(file1).Length}, got {alpha.Size}");
        });

        Console.WriteLine();
        Console.WriteLine($"[ZipExtensionTest] Done. {pass} passed, {fail} failed.");
        if (fail > 0) throw new Exception($"{fail} zip tests failed.");
    }
}
