// Copyright 2025 Chuvadi Contributors
// SPDX-License-Identifier: Apache-2.0
// PHASE: Phase 1.1.4 — Tests for RsaVerifier
//
// Test vectors generated by Python's cryptography library (which uses
// OpenSSL under the hood). The public key is parsed, then signatures
// computed externally are verified.

using System;
using Chuvadi.Cryptography.Hashing;
using Chuvadi.Cryptography.PublicKey;
using FluentAssertions;
using Xunit;

namespace Chuvadi.Cryptography.Tests.PublicKey;

public sealed class RsaVerifierTests
{
    // RSA 2048-bit public key (PKCS#1 RSAPublicKey DER, hex)
    private const string RsaPubKeyHex =
        "3082010a0282010100af2a53aa39c398298e056acc8b0052efaf9909c97a25a44e91b604598daabd" +
        "8a4b2934993f1f6351ff6661fb484f33d798c20c3e31010b29ad778270536d58f4fb0fd4ac1d4c15" +
        "f30327ea5dc8f955c0acc2ab4f9cbca8ed05ad8643147e0422581e97eb2edafdee91320b49d05de6" +
        "6b5690fafb46bfd4f82a66e6512a745b8963766477b195a6eae510ccae8da41d8a80582dc1472ba6" +
        "24874ff8313ec9a3ca10619d7ae9d72d67fdc72929582c40e134302c84534c73d3acd80d3395c913" +
        "e36451c33b8345dff64b5b3b1411774e7a839de409f2f187495244e792070f47c3a54e1231a391d2" +
        "729694272e4fe22e0e37d2fbab0b5ac527f69c207f6e9a52090203010001";

    private static RsaPublicKey LoadKey() =>
        RsaPublicKey.FromSubjectPublicKey(Convert.FromHexString(RsaPubKeyHex));

    [Fact]
    public void Verify_PkcsV15_sha256_Valid()
    {
        var key = LoadKey();
        byte[] hash = Convert.FromHexString(
            "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592");
        byte[] sig = Convert.FromHexString(
            "6c764641074117c49542669fc671cb3f1f56f100d6a726152a9511f5d4b604ae639e9b4584241c7b" +
            "17d451696a12888d03ace376320a750b4f442881837bcb9c8fe43c5a8b1befcb8dc3a4a93fb0c053" +
            "0b543ccf08cff2ec37e936484746fbfa6b9c7913548e6e36926017cb762919d997e0dc733dd893ea" +
            "bb8e94c8bbd1a55fa4bd37b02fbb3e585ff6d1387bc9235f1ef401c3b084ca6cb2d0e503c87cfaa0" +
            "f71c61b081fc6c242283184faf1991448f96aa82a66b5ca64113f7106a2185ecefebb59e435fa4d4" +
            "684644031c1b581e7ef3e255dee4e98bfb260ad5b320fbbe549981ef8fa8ac5ff14ea63669f0b6f4" +
            "8fdb09fb37308cc4adafe25ffb6cbcb5");
        bool result = RsaVerifier.VerifyPkcs1v15(key, HashAlgorithmName.Sha256, hash, sig);
        result.Should().Be(true);
    }

    [Fact]
    public void Verify_PkcsV15_sha256_Corrupted()
    {
        var key = LoadKey();
        byte[] hash = Convert.FromHexString(
            "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592");
        byte[] sig = Convert.FromHexString(
            "6c764641074117c49542679fc671cb3f1f56f100d6a726152a9511f5d4b604ae639e9b4584241c7b" +
            "17d451696a12888d03ace376320a750b4f442881837bcb9c8fe43c5a8b1befcb8dc3a4a93fb0c053" +
            "0b543ccf08cff2ec37e936484746fbfa6b9c7913548e6e36926017cb762919d997e0dc733dd893ea" +
            "bb8e94c8bbd1a55fa4bd37b02fbb3e585ff6d1387bc9235f1ef401c3b084ca6cb2d0e503c87cfaa0" +
            "f71c61b081fc6c242283184faf1991448f96aa82a66b5ca64113f7106a2185ecefebb59e435fa4d4" +
            "684644031c1b581e7ef3e255dee4e98bfb260ad5b320fbbe549981ef8fa8ac5ff14ea63669f0b6f4" +
            "8fdb09fb37308cc4adafe25ffb6cbcb5");
        bool result = RsaVerifier.VerifyPkcs1v15(key, HashAlgorithmName.Sha256, hash, sig);
        result.Should().Be(false);
    }

    [Fact]
    public void Verify_Pss_sha256_Valid()
    {
        var key = LoadKey();
        byte[] hash = Convert.FromHexString(
            "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592");
        byte[] sig = Convert.FromHexString(
            "965e2a21f622545c8c41712fdb6ee00ea60413524e42f134f0093aa709c07f0dbf7c7c7bd446eec6" +
            "39fe51491e1e517113840fc7f69c8112c6bcb97cb1967bb7f2cdccd44dbdfe93980af946f3b5772a" +
            "3da3f1556b035bed8b705e4a11dea0e7531b20cfed8dee978f737188a906e37f724b84c60b46d3d6" +
            "1d3839073238b98bdbc62644fea1b36ca9f4d78770be96971e7b98c9b60b8e45b088f51eac31d0e3" +
            "6e4aa925dcb42400034a917be2545bfff95fcf9dc323aa0d63c1774d1dc84ce5e4fbcf6a92233e43" +
            "f8688cc6116cacf5ebcef31a48e93ad7f31847fc62d7179935c3539e2077707786361dd02732d563" +
            "000680b3bcb6acf9141c9fd961ca5b29");
        bool result = RsaVerifier.VerifyPss(key, HashAlgorithmName.Sha256, HashAlgorithmName.Sha256, 32, hash, sig);
        result.Should().Be(true);
    }

    [Fact]
    public void Verify_PkcsV15_sha384_Valid()
    {
        var key = LoadKey();
        byte[] hash = Convert.FromHexString(
            "ca737f1014a48f4c0b6dd43cb177b0afd9e5169367544c494011e3317dbf9a509cb1e5dc1e85a941" +
            "bbee3d7f2afbc9b1");
        byte[] sig = Convert.FromHexString(
            "7904cedfded3fe7c24d3c6c4b83993e654bc8fd9abbeea5c5e3d7f04af31efb5ffdd0aeaabbd9b15" +
            "3b9a493bfe2c04b364249431998c3e304c13293f31366143ae3f651287fb9bb15e4f750edbe25b3f" +
            "276d9e038db586c3591a8506b446d716107f2506f69687cb6190f1226b308738d088e1b54fa5b182" +
            "9ca09e50180eba1937c0f3da70c92274e18669fd1848d4a074d3f52d39405c290cf6e45b1f663958" +
            "3dced89767af564ca5fe4bd2b9d0da5f9cd392b6480360e79e9eb8966241db4d79dd7fc65aae9c94" +
            "f838cff7b845ce925a09aed8d8a700c831202fa847bdd25a1dbed13105dcae072b23234e536afa53" +
            "344328248559d5187bffbdb530f2f208");
        bool result = RsaVerifier.VerifyPkcs1v15(key, HashAlgorithmName.Sha384, hash, sig);
        result.Should().Be(true);
    }

    [Fact]
    public void Verify_PkcsV15_sha512_Valid()
    {
        var key = LoadKey();
        byte[] hash = Convert.FromHexString(
            "07e547d9586f6a73f73fbac0435ed76951218fb7d0c8d788a309d785436bbb642e93a252a954f239" +
            "12547d1e8a3b5ed6e1bfd7097821233fa0538f3db854fee6");
        byte[] sig = Convert.FromHexString(
            "2d2b9ddf31e9fce918973567b47584a6c0e6771b76ca6ffef7911ee4a77eac195cb439cfdd833865" +
            "bf17fb960e18ed9e49ad0b06906dc3b50dbeeb6e38b698fb079800508185ebf72cb34d9aa96c7d5e" +
            "02861004ebd8970c7ed7edbe7915135a52b4c620bb6a32e073dc09a8659ac1aa021a98ef6c29b21c" +
            "65163725aebdd5c1e636a2351a42a4b4fcf2a51f9124c2f8a789c7e7d13d335e245fddd826999688" +
            "f01115bbdf8f535321be240c23b6fd64b3ad93f0ee6458e723817ac6a736994833dca697b2d0acbc" +
            "c4e9d6c3135f586628dc29b5d4573fcd4857176602c6a90cfe3f2d956456c25e2c123ca55ee752e5" +
            "41695027c4cec3c0924ab4ed0b4f4e0d");
        bool result = RsaVerifier.VerifyPkcs1v15(key, HashAlgorithmName.Sha512, hash, sig);
        result.Should().Be(true);
    }

    [Fact]
    public void Verify_PkcsV15_SignatureWrongSize_ReturnsFalse()
    {
        var key = LoadKey();
        byte[] hash = new byte[32];
        byte[] sigWrongSize = new byte[100];  // not 256 bytes
        bool result = RsaVerifier.VerifyPkcs1v15(key, HashAlgorithmName.Sha256, hash, sigWrongSize);
        result.Should().BeFalse();
    }

    [Fact]
    public void Verify_PkcsV15_WrongHashLength_ReturnsFalse()
    {
        var key = LoadKey();
        byte[] hash = new byte[20];  // wrong size for SHA-256
        byte[] sig = new byte[256];
        bool result = RsaVerifier.VerifyPkcs1v15(key, HashAlgorithmName.Sha256, hash, sig);
        result.Should().BeFalse();
    }

    [Fact]
    public void RsaPublicKey_FromSubjectPublicKey_RoundTrips()
    {
        var key = LoadKey();
        key.Algorithm.Should().Be(PublicKeyAlgorithm.Rsa);
        key.Modulus.Sign.Should().Be(1);
        key.PublicExponent.Sign.Should().Be(1);
        key.ModulusSizeBytes.Should().Be(256);  // 2048 bits
    }

    [Fact]
    public void RsaPublicKey_NegativeModulus_Throws()
    {
        Action act = () => new RsaPublicKey(-1, 65537);
        act.Should().Throw<ArgumentException>();
    }
}
