#!/usr/bin/env python3
# Copyright 2025 Chuvadi Contributors
# SPDX-License-Identifier: Apache-2.0
# Regenerates src/Chuvadi.Pdf.Fonts.Rendering/CffStandardStrings.cs from
# fontTools' canonical CFF Standard Strings table (Adobe TN #5176 Appendix A).
# Offline: reads the constant bundled in fontTools; no network access.
from pathlib import Path
from fontTools.cffLib import cffStandardStrings as S

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "src" / "Chuvadi.Pdf.Fonts.Rendering" / "CffStandardStrings.cs"

def main():
    assert len(S) == 391, f"expected 391 standard strings, got {len(S)}"
    rows = "\n".join('        "%s",' % s.replace("\\","\\\\").replace('"','\\"') for s in S)
    text = HEADER + rows + FOOTER
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(S)} strings)")

HEADER = """// Copyright 2025 Chuvadi Contributors
// SPDX-License-Identifier: Apache-2.0
// <auto-generated>
//   CFF Standard Strings (Adobe Technical Note #5176, Appendix A).
//   The 391 predefined strings addressed by SIDs 0..390. SIDs >= 391 index
//   the font's String INDEX (sid - 391). Regenerate via tools/gen_cff_standard_strings.py.
// </auto-generated>
#nullable enable

namespace Chuvadi.Pdf.Fonts.Rendering;

/// <summary>
/// The 391 CFF Standard Strings (SIDs 0..390) defined in Adobe Technical
/// Note #5176, Appendix A. String identifiers (SIDs) below
/// <see cref="Count"/> resolve here; higher SIDs index the font's String INDEX.
/// </summary>
internal static class CffStandardStrings
{
    /// <summary>The number of standard strings (391).</summary>
    public static int Count => Strings.Length;

    /// <summary>
    /// Resolves a standard-string SID to its name, or <c>null</c> when the SID
    /// is outside the standard range.
    /// </summary>
    /// <param name="sid">The string identifier.</param>
    public static string? Get(int sid)
    {
        if (sid < 0 || sid >= Strings.Length) { return null; }
        return Strings[sid];
    }

    private static readonly string[] Strings =
    {
"""
FOOTER = "\n    };\n}\n"

if __name__ == "__main__":
    main()
