#!/usr/bin/env python3
"""Generate src/Chuvadi.Pdf.Fonts.Rendering/AdobeGlyphList.cs from the vendored AGL.

Reads the Adobe Glyph List (AGL) version 2.0 from the repo-local, vendored copy at
tools/agl/glyphlist.txt and emits a faithful, complete C# source file containing the
name->scalar tables and the GlyphNameToUnicode resolver.

This tool performs NO network access. The vendored list is the single source of truth;
to refresh it, replace tools/agl/glyphlist.txt manually and re-run this script.

Regenerate via:
    python tools/gen_adobe_glyph_list.py
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGL_PATH = REPO_ROOT / "tools" / "agl" / "glyphlist.txt"
OUT_PATH = REPO_ROOT / "src" / "Chuvadi.Pdf.Fonts.Rendering" / "AdobeGlyphList.cs"
AGL_SOURCE_NOTE = "Adobe Glyph List (AGL) v2.0, vendored at tools/agl/glyphlist.txt"


def parse(text):
    single, seq = [], []
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        name, vals = line.split(";", 1)
        cps = [int(x, 16) for x in vals.split()]
        if any(cp > 0xFFFF for cp in cps):
            raise ValueError("non-BMP scalar in vendored list: " + line)
        (single if len(cps) == 1 else seq).append((name, cps))
    return single, seq


def emit(single, seq):
    total = len(single) + len(seq)
    out = []
    a = out.append
    a("// <auto-generated>")
    a("//     This file was generated from the canonical Adobe Glyph List (AGL).")
    a("//     AGL table version: 2.0  (Copyright 2002-2019 Adobe).")
    a("//     Source: " + AGL_SOURCE_NOTE)
    a("//     Entries: %d (%d single scalar, %d multi-scalar sequence)." % (total, len(single), len(seq)))
    a("//     Do not edit by hand. Regenerate via tools/gen_adobe_glyph_list.py.")
    a("// </auto-generated>")
    a("")
    a("#nullable enable")
    a("")
    a("using System;")
    a("using System.Collections.Generic;")
    a("")
    a("namespace Chuvadi.Pdf.Fonts.Rendering;")
    a("")
    a("/// <summary>")
    a("/// Provides the canonical Adobe Glyph List (AGL) version 2.0, mapping PostScript")
    a("/// glyph names to their Unicode scalar values. All scalar values in the list lie")
    a("/// within the Basic Multilingual Plane.")
    a("/// </summary>")
    a("public static class AdobeGlyphList")
    a("{")
    a("    private static readonly Dictionary<string, int> SingleMap = new(%d)" % len(single))
    a("    {")
    for name, cps in single:
        a('        { "%s", 0x%04X },' % (name, cps[0]))
    a("    };")
    a("")
    a("    private static readonly Dictionary<string, int[]> SequenceMap = new(%d)" % len(seq))
    a("    {")
    for name, cps in seq:
        a('        { "%s", new[] { %s } },' % (name, ", ".join("0x%04X" % cp for cp in cps)))
    a("    };")
    a("")
    a("    /// <summary>Gets the total number of glyph-name entries in the list.</summary>")
    a("    public static int Count => SingleMap.Count + SequenceMap.Count;")
    a("")
    a("    /// <summary>")
    a("    /// Attempts to resolve a glyph name to a single Unicode scalar value via a direct")
    a("    /// lookup in the Adobe Glyph List. Names that are absent, or that map to a sequence")
    a('    /// of more than one scalar value, yield <see langword="false"/>.')
    a("    /// </summary>")
    a('    /// <param name="glyphName">The PostScript glyph name to look up.</param>')
    a('    /// <param name="codePoint">When this method returns <see langword="true"/>, the resolved scalar value.</param>')
    a('    /// <returns><see langword="true"/> if the name maps to exactly one scalar value; otherwise <see langword="false"/>.</returns>')
    a("    public static bool TryGetCodePoint(string glyphName, out int codePoint)")
    a("    {")
    a("        ArgumentNullException.ThrowIfNull(glyphName);")
    a("        return SingleMap.TryGetValue(glyphName, out codePoint);")
    a("    }")
    a("")
    a("    /// <summary>")
    a("    /// Attempts to resolve a glyph name to its full Unicode scalar value sequence via a")
    a("    /// direct lookup in the Adobe Glyph List. Most names map to a single scalar value;")
    a("    /// a small number of presentation forms map to a sequence.")
    a("    /// </summary>")
    a('    /// <param name="glyphName">The PostScript glyph name to look up.</param>')
    a('    /// <param name="codePoints">When this method returns <see langword="true"/>, the resolved scalar value sequence.</param>')
    a('    /// <returns><see langword="true"/> if the name is present in the list; otherwise <see langword="false"/>.</returns>')
    a("    public static bool TryGetCodePoints(string glyphName, out IReadOnlyList<int> codePoints)")
    a("    {")
    a("        ArgumentNullException.ThrowIfNull(glyphName);")
    a("        if (SingleMap.TryGetValue(glyphName, out int single))")
    a("        {")
    a("            codePoints = new[] { single };")
    a("            return true;")
    a("        }")
    a("")
    a("        if (SequenceMap.TryGetValue(glyphName, out int[]? sequence))")
    a("        {")
    a("            codePoints = sequence;")
    a("            return true;")
    a("        }")
    a("")
    a("        codePoints = Array.Empty<int>();")
    a("        return false;")
    a("    }")
    a("")
    a("    /// <summary>")
    a("    /// Determines whether the specified glyph name is present in the Adobe Glyph List.")
    a("    /// </summary>")
    a('    /// <param name="glyphName">The PostScript glyph name to test.</param>')
    a('    /// <returns><see langword="true"/> if the name is present; otherwise <see langword="false"/>.</returns>')
    a("    public static bool Contains(string glyphName)")
    a("    {")
    a("        ArgumentNullException.ThrowIfNull(glyphName);")
    a("        return SingleMap.ContainsKey(glyphName) || SequenceMap.ContainsKey(glyphName);")
    a("    }")
    a("}")
    a("")
    a(RESOLVER)
    return "\n".join(out)


RESOLVER = r'''/// <summary>
/// Implements the Adobe Glyph List algorithm for deriving Unicode scalar values from a
/// glyph name. The algorithm drops any suffix beginning at the first period, splits the
/// remainder on underscores into ligature components, and maps each component via a direct
/// Adobe Glyph List lookup, the <c>uniXXXX</c> form, or the <c>uXXXX..</c> form.
/// </summary>
/// <remarks>
/// The <c>uniXXXX</c> and <c>uXXXX..</c> forms require uppercase hexadecimal digits, as
/// mandated by the Adobe Glyph List specification. Non-conformant lowercase forms are not
/// recognised and resolve to nothing.
/// </remarks>
public static class GlyphNameToUnicode
{
    private const string UniPrefix = "uni";

    /// <summary>
    /// Resolves a glyph name to its Unicode scalar value sequence using the Adobe Glyph
    /// List algorithm. Components that cannot be resolved contribute nothing to the result,
    /// so an entirely unresolvable name yields an empty sequence.
    /// </summary>
    /// <param name="glyphName">The PostScript glyph name to resolve.</param>
    /// <returns>The resolved sequence of Unicode scalar values, which may be empty.</returns>
    public static IReadOnlyList<int> Resolve(string glyphName)
    {
        ArgumentNullException.ThrowIfNull(glyphName);

        int periodIndex = glyphName.IndexOf('.', StringComparison.Ordinal);
        string stem = periodIndex >= 0 ? glyphName.Substring(0, periodIndex) : glyphName;
        if (stem.Length == 0)
        {
            return Array.Empty<int>();
        }

        string[] components = stem.Split('_');
        List<int> result = new(components.Length);
        foreach (string component in components)
        {
            AppendComponent(component, result);
        }

        return result;
    }

    /// <summary>
    /// Resolves a glyph name to a single Unicode scalar value, returning <see langword="null"/>
    /// when the name resolves to nothing or to more than one scalar value.
    /// </summary>
    /// <param name="glyphName">The PostScript glyph name to resolve.</param>
    /// <returns>The single resolved scalar value, or <see langword="null"/>.</returns>
    public static int? ResolveSingle(string glyphName)
    {
        ArgumentNullException.ThrowIfNull(glyphName);

        IReadOnlyList<int> resolved = Resolve(glyphName);
        return resolved.Count == 1 ? resolved[0] : null;
    }

    private static void AppendComponent(string component, List<int> output)
    {
        if (component.Length == 0)
        {
            return;
        }

        if (AdobeGlyphList.TryGetCodePoints(component, out IReadOnlyList<int> mapped))
        {
            for (int i = 0; i < mapped.Count; i++)
            {
                output.Add(mapped[i]);
            }

            return;
        }

        if (TryAppendUniForm(component, output))
        {
            return;
        }

        if (TryParseUForm(component, out int scalar))
        {
            output.Add(scalar);
        }
    }

    private static bool TryAppendUniForm(string component, List<int> output)
    {
        if (!component.StartsWith(UniPrefix, StringComparison.Ordinal))
        {
            return false;
        }

        string digits = component.Substring(UniPrefix.Length);
        if (digits.Length == 0 || digits.Length % 4 != 0)
        {
            return false;
        }

        List<int> parsed = new(digits.Length / 4);
        for (int i = 0; i < digits.Length; i += 4)
        {
            if (!TryParseHex(digits, i, 4, out int value) || !IsBmpScalar(value))
            {
                return false;
            }

            parsed.Add(value);
        }

        for (int i = 0; i < parsed.Count; i++)
        {
            output.Add(parsed[i]);
        }

        return true;
    }

    private static bool TryParseUForm(string component, out int scalar)
    {
        scalar = 0;
        if (component.Length < 5 || component[0] != 'u')
        {
            return false;
        }

        int digitCount = component.Length - 1;
        if (digitCount < 4 || digitCount > 6)
        {
            return false;
        }

        if (!TryParseHex(component, 1, digitCount, out int value) || value > 0x10FFFF)
        {
            return false;
        }

        scalar = value;
        return true;
    }

    private static bool TryParseHex(string text, int start, int length, out int value)
    {
        value = 0;
        for (int i = start; i < start + length; i++)
        {
            char c = text[i];
            int digit;
            if (c >= '0' && c <= '9')
            {
                digit = c - '0';
            }
            else if (c >= 'A' && c <= 'F')
            {
                digit = 10 + (c - 'A');
            }
            else
            {
                return false;
            }

            value = (value << 4) | digit;
        }

        return true;
    }

    private static bool IsBmpScalar(int value)
    {
        return (value >= 0x0000 && value <= 0xD7FF) || (value >= 0xE000 && value <= 0xFFFF);
    }
}
'''


def main():
    if not AGL_PATH.is_file():
        print("error: vendored AGL not found at %s" % AGL_PATH, file=sys.stderr)
        return 1
    text = AGL_PATH.read_text(encoding="utf-8")
    single, seq = parse(text)
    sd = {n: c for n, c in single}
    for name, expected in (("A", 0x0041), ("checkmark", 0x2713), ("Euro", 0x20AC)):
        if sd.get(name) != [expected]:
            print("spot-check FAILED: %s -> %s" % (name, sd.get(name)), file=sys.stderr)
            return 1
    code = emit(single, seq)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(code, encoding="utf-8", newline="\n")
    print("Wrote %s (%d entries)" % (OUT_PATH, len(single) + len(seq)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
