using System;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Chuvadi.Sheets.Zip;

/// <summary>
/// Streaming zip writer. Construct with <see cref="Create(string, CompressionLevel)"/> or
/// <see cref="Create(System.IO.Stream, CompressionLevel, bool)"/>, add entries via
/// <see cref="AddFile"/>/<see cref="AddStream"/>/<see cref="AddText"/>, then dispose.
///
/// <code>
/// using (var zip = ZipWriter.Create("bundle.zip"))
/// {
///     zip.AddFile("report.pdf", "C:\\out\\report.pdf");
///     zip.AddText("readme.txt", "Generated by Chuvadi.Sheets");
/// }
/// </code>
///
/// Thread-safety: NOT thread-safe. Use one writer per thread.
/// </summary>
public sealed class ZipWriter : IDisposable, IAsyncDisposable
{
    private readonly Stream _outputStream;
    private readonly bool _ownsOutputStream;
    private readonly ZipArchive _archive;
    private readonly CompressionLevel _compressionLevel;
    private bool _disposed;

    private ZipWriter(Stream output, bool ownsStream, CompressionLevel level)
    {
        _outputStream = output;
        _ownsOutputStream = ownsStream;
        _compressionLevel = level;
        _archive = new ZipArchive(output, ZipArchiveMode.Create, leaveOpen: !ownsStream);
    }

    // ---- Construction --------------------------------------------------------------

    /// <summary>Creates a writer streaming to the given file path. The file is created or overwritten.</summary>
    public static ZipWriter Create(string path, CompressionLevel level = CompressionLevel.Optimal)
    {
        if (string.IsNullOrEmpty(path)) throw new ArgumentException("Path required.", nameof(path));
        var stream = new FileStream(
            path, FileMode.Create, FileAccess.Write, FileShare.None,
            bufferSize: 64 * 1024,
            options: FileOptions.Asynchronous);
        try
        {
            return new ZipWriter(stream, ownsStream: true, level);
        }
        catch
        {
            stream.Dispose();
            throw;
        }
    }

    /// <summary>Creates a writer streaming to the given stream.</summary>
    /// <param name="output">The writable stream to receive the archive bytes.</param>
    /// <param name="level">Compression level applied to entries (default Optimal).</param>
    /// <param name="leaveOpen">If true (default), the underlying stream is NOT closed when the writer disposes.</param>
    public static ZipWriter Create(Stream output, CompressionLevel level = CompressionLevel.Optimal, bool leaveOpen = true)
    {
        if (output is null) throw new ArgumentNullException(nameof(output));
        return new ZipWriter(output, ownsStream: !leaveOpen, level);
    }

    // ---- Add entries (sync) --------------------------------------------------------

    /// <summary>Adds a file from disk to the archive under the given entry name.</summary>
    public ZipWriter AddFile(string entryName, string sourcePath)
    {
        EnsureNotDisposed();
        ValidateEntryName(entryName);
        if (string.IsNullOrEmpty(sourcePath)) throw new ArgumentException("Source path required.", nameof(sourcePath));

        var entry = _archive.CreateEntry(NormalizeEntryName(entryName), _compressionLevel);
        try
        {
            entry.LastWriteTime = new DateTimeOffset(File.GetLastWriteTimeUtc(sourcePath), TimeSpan.Zero);
        }
        catch { /* ignore — timestamps are advisory */ }

        using var dest = entry.Open();
        using var src = new FileStream(sourcePath, FileMode.Open, FileAccess.Read, FileShare.Read);
        src.CopyTo(dest);
        return this;
    }

    /// <summary>Adds an entry whose content comes from a stream. The stream is read from its current position to its end.</summary>
    public ZipWriter AddStream(string entryName, Stream content)
    {
        EnsureNotDisposed();
        ValidateEntryName(entryName);
        if (content is null) throw new ArgumentNullException(nameof(content));

        var entry = _archive.CreateEntry(NormalizeEntryName(entryName), _compressionLevel);
        using var dest = entry.Open();
        content.CopyTo(dest);
        return this;
    }

    /// <summary>Adds an entry whose content is the UTF-8 encoded form of <paramref name="text"/>.</summary>
    public ZipWriter AddText(string entryName, string text, Encoding? encoding = null)
    {
        EnsureNotDisposed();
        ValidateEntryName(entryName);
        if (text is null) throw new ArgumentNullException(nameof(text));

        var enc = encoding ?? new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
        var entry = _archive.CreateEntry(NormalizeEntryName(entryName), _compressionLevel);
        using var dest = entry.Open();
        using var w = new StreamWriter(dest, enc);
        w.Write(text);
        return this;
    }

    /// <summary>Adds an entry whose content is raw bytes.</summary>
    public ZipWriter AddBytes(string entryName, byte[] data)
    {
        EnsureNotDisposed();
        ValidateEntryName(entryName);
        if (data is null) throw new ArgumentNullException(nameof(data));

        var entry = _archive.CreateEntry(NormalizeEntryName(entryName), _compressionLevel);
        using var dest = entry.Open();
        dest.Write(data, 0, data.Length);
        return this;
    }

    // ---- Add entries (async) -------------------------------------------------------

    public async Task<ZipWriter> AddFileAsync(string entryName, string sourcePath, CancellationToken ct = default)
    {
        EnsureNotDisposed();
        ValidateEntryName(entryName);
        if (string.IsNullOrEmpty(sourcePath)) throw new ArgumentException("Source path required.", nameof(sourcePath));

        var entry = _archive.CreateEntry(NormalizeEntryName(entryName), _compressionLevel);
        try { entry.LastWriteTime = new DateTimeOffset(File.GetLastWriteTimeUtc(sourcePath), TimeSpan.Zero); }
        catch { }

        await using var dest = entry.Open();
        await using var src = new FileStream(
            sourcePath, FileMode.Open, FileAccess.Read, FileShare.Read,
            bufferSize: 64 * 1024, options: FileOptions.Asynchronous);
        await src.CopyToAsync(dest, ct).ConfigureAwait(false);
        return this;
    }

    public async Task<ZipWriter> AddStreamAsync(string entryName, Stream content, CancellationToken ct = default)
    {
        EnsureNotDisposed();
        ValidateEntryName(entryName);
        if (content is null) throw new ArgumentNullException(nameof(content));

        var entry = _archive.CreateEntry(NormalizeEntryName(entryName), _compressionLevel);
        await using var dest = entry.Open();
        await content.CopyToAsync(dest, ct).ConfigureAwait(false);
        return this;
    }

    // ---- Helpers -------------------------------------------------------------------

    /// <summary>
    /// Validates an entry name. Disallows: empty, absolute paths, drive letters, '..' segments
    /// (path-traversal protection on the WRITE side — produced zips shouldn't smuggle ../).
    /// </summary>
    private static void ValidateEntryName(string name)
    {
        if (string.IsNullOrEmpty(name))
            throw new ArgumentException("Entry name cannot be null or empty.", nameof(name));
        // Absolute paths and drive letters are disallowed regardless of separator.
        if (name[0] == '/' || name[0] == '\\')
            throw new ArgumentException($"Entry name cannot be absolute: '{name}'.", nameof(name));
        if (name.Length >= 2 && name[1] == ':')
            throw new ArgumentException($"Entry name cannot contain a drive letter: '{name}'.", nameof(name));

        // Reject '..' segments.
        // Tokenize on both '/' and '\\' to be defensive.
        var spans = name.Replace('\\', '/').Split('/');
        foreach (var seg in spans)
        {
            if (seg == "..")
                throw new ArgumentException($"Entry name cannot contain '..' segments: '{name}'.", nameof(name));
        }
    }

    /// <summary>Normalizes entry name to forward-slash form, which is the zip-spec preference.</summary>
    private static string NormalizeEntryName(string name)
        => name.Replace('\\', '/');

    private void EnsureNotDisposed() => ObjectDisposedException.ThrowIf(_disposed, this);

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;

        try { _archive.Dispose(); } catch { }
        if (_ownsOutputStream)
        {
            try { _outputStream.Dispose(); } catch { }
        }
    }

    public ValueTask DisposeAsync()
    {
        Dispose();
        return ValueTask.CompletedTask;
    }
}
